apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-download
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hetzner_demo
  source:
    repoURL: https://github.com/sibinnediyoram/demo_repository
    targetRevision: main
    path: hetzner_demo_case/kubernetes/apps/media-download
  destination:
    server: https://kubernetes.default.svc
    namespace: hetzner_demo-download
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
