apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: media-search
  namespace: hetzner_demo-search
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: media-search
  namespace: hetzner_demo-search
subjects:
  - kind: ServiceAccount
    name: media-search
    namespace: hetzner_demo-search
roleRef:
  kind: Role
  name: media-search
  apiGroup: rbac.authorization.k8s.io
