apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: imago
  source:
    repoURL: https://github.com/sibinnediyoram/demo_repository
    targetRevision: main
    path: imago_case/kubernetes/apps/web-app
  destination:
    server: https://kubernetes.default.svc
    namespace: imago-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
