apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: imago
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: IMAGO media platform services
  sourceRepos:
    - https://github.com/sibinnediyoram/demo_repository
  destinations:
    - namespace: imago-web
      server: https://kubernetes.default.svc
    - namespace: imago-search
      server: https://kubernetes.default.svc
    - namespace: imago-download
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ConfigMap
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: networking.k8s.io
      kind: Ingress
    - group: traefik.io
      kind: IngressRoute
    - group: traefik.io
      kind: Middleware
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: policy
      kind: PodDisruptionBudget
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
  roles:
    - name: read-only
      description: Read-only access for developers
      policies:
        - p, proj:imago:read-only, applications, get, imago/*, allow
      groups:
        - imago-devs
