apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: media-download
  namespace: hetzner_demo-download
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: media-download
  namespace: hetzner_demo-download
subjects:
  - kind: ServiceAccount
    name: media-download
    namespace: hetzner_demo-download
roleRef:
  kind: Role
  name: media-download
  apiGroup: rbac.authorization.k8s.io
